services:
  file-server:
    build: .
    restart: always
    container_name: file-server
    network_mode: host
    volumes:
      - /data/files:/data/files
      - /tmp/uploadedFiles:/tmp/uploadedFiles
    expose:
      - "3000"
